config/routes.rb
Rails.application.routes.draw do
  # MF-CLIENT - ROUTES.RB

  # Main
  root :to => 'main_interface#index'
  get '/campaign/:campaign_id', to: 'main_interface#campaign'
  get '/campaigns', to: 'main_interface#campaigns'
  get '/new_campaign', to: 'main_interface#new_campaign'
  get '/create_campaign', to: 'main_interface#create_campaign'
  get '/edit_campaign/:id', to: 'main_interface#edit_campaign'
  get '/job/:id', to: 'main_interface#job'

  # Funnel-Builder
  get '/funnel/:campaign_id', to: 'funnel_builder#index'
  get '/funnel', to: 'funnel_builder#index'
  get '/mainfb/', to: 'funnel_builder#superfunnel'

  # Funnel-Builder JSON API
  post '/fbapi_index' => 'funnel_builder#api_index'
  post '/fbapi_update' => 'funnel_builder#api_update'
  post '/fbapi_read' => 'funnel_builder#api_read'
  post '/fbapi_create' => 'funnel_builder#api_create'
  post '/fbapi_delete' => 'funnel_builder#api_delete'
  post '/fbapi_update_email_list' => 'funnel_builder#api_update_list' #API Route to update Campaigns Email List

  get '/campaignjobs/:id', to: 'campaigns#viewcampaignjobs'

  # Email Controller
  get '/lists', to: 'email#lists'
  get '/emails/:list_id', to: 'email#emails'
  get '/new_list', to: 'email#new_list'
  match '/create_list' => 'email#create_list', via: [:post]

  # Scaffolds
  # resources :mail_funnel_configs
  # resources :email_lists

  # Shopify Routes
  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'

  mount ShopifyApp::Engine, at: '/'

  # namespace :app_proxy do
  #   root action: 'index'
    # simple routes without a specified controller will go to AppProxyController

    # resources :hooks_constants
    # resources :users
      # resources :campaigns

    # more complex routes will go to controllers in the AppProxy namespace
    # 	resources :reviews
    # GET /app_proxy/reviews will now be routed to
    # AppProxy::ReviewsController#index, for example
  # end
end

app/controllers/funnel_builder_controller.rb
require 'htmlentities'
require 'JobLocal'
require 'date'

# TODO: Funnel-Builer: Account for empty data here

class FunnelBuilderController < ShopifyApp::AuthenticatedController

	def api_read

		id = params[:job_id]

		j = Job.find(id)

		#job_queue = JobQueue.where(queue_identifier: j.queue_identifier.to_s)

		#logger.debug job_queue

		job_json =  j.to_json
		#job_q_json = job_queue.to_json 

		#result = job_json + job_q_json

		#logger.debug 'Funnel-Builder INDEX VIEW JOB: ' + result.to_s

		render json: job_json
	end

	def api_index

		width       = params[:width]
		campaign_id = params[:campaign_id] # Not used yet

		app_param = params[:app_id]
		app       = App.find(app_param)
		appid     = app.id

		@email_lists = EmailList.where(app_id: appid)

		@local_jobs = Array.new

		left          = 0
		top           = 0
		top_increment = 125 #Top Increment

		operators = Hash.new

		# TODO: Convert all Hash Keys to :key format and change from ' to ' single quotes

		campaign  = Campaign.find(campaign_id)

		operators['campaign_0'] =
			 {
					:top                  => top.to_s,
					:left                 => left.to_s,
					:multipleLinksOnInput => 'true',
					:properties           => {
						 :title   => 'Campaign',
						 :inputs  => {},
						 :outputs => {
							  :output_1 => {
								   :label => campaign.name + ' Jobs:',
								}
						 }
					}
			 }

		top   += (top_increment - 28) #First Link doesn't have all boxes so adjust the first link by size of box (28px)

		# TODO: Dynamically calculate a column-count from page-width param

		count = 0 # TODO: Add app_id again - app_id: appid,
		Job.where(campaign_id: campaign.id).each do |j|
			p 'Adding Job ID ' + appid.to_s

			jl                      = JobLocal.new
			jl.local_identifier     = 'job_' + j.id.to_s
			jl.name                 = j.name

			jl.hook_identifier      = campaign.hook_identifier
			jl.hook_id              = j.hook_id
			jl.campaign_id          = j.campaign_id

			jl.subject              = j.subject
			jl.content              = j.content

			jl.email_list_id        = j.email_list_id
			jl.app_id               = j.app_id
			jl.executed             = j.executed
			jl.created_at           = j.created_at
			jl.updated_at           = j.updated_at
			jl.execute_time         = j.execute_time
			jl.execute_set_time     = j.execute_set_time

			total_revenue = 0
			CampaignProductLead.where(job_id: j.id, sold: true, app_id: appid).each do |cel|
				total_revenue += cel.sale_ammount
			end
			jl.total_revenue        = total_revenue

			# Add the execute time to the time it was created to find the next execute time
			date = DateTime.parse(jl.created_at) # Convert Timestamp to DateTime Object
			add_time = jl.execute_time # Get jobs execute time
			date = date + add_time.hours # Add jobs execute time to DateTime Object
			label = date.strftime('%c')
			
			if jl.executed == true
				executedstring = 'Executed ' + j.execute_set_time
			else
				executedstring = jl.execute_time.to_s + ' hours'
			end

			@local_jobs << jl

			if operator_title = (jl.local_identifier).to_s
				operators[operator_title] =
					 {
							'top'                  => top.to_s,
							'left'                 => left.to_s,
							'multipleLinksOnInput' => 'false',
							'properties'           => {
								 'title'   => j.name,
								 'inputs'  => {
										'input_1' => {
											 'label' => ''
										}
								 },
								 'outputs' => {
										'output_1' => {
											 'label' => executedstring.html_safe
										}
								 }
							}
					 }
				count                     += 1
				top                       += top_increment
			end
		end

		connections = Hash.new
		link_count  = 0
		last_job_id = 0
		firstjob    = true

		Job.where(campaign_id: campaign.id).each do |j|
			connector_title = ('link_' + link_count.to_s).to_s
			if firstjob
				connections[connector_title] =
					 {
							'fromOperator'  => 'campaign_0',
							'fromConnector' => 'output_1',
							'toOperator'    => 'job_' + j.id.to_s,
							'toConnector'   => 'input_1'
					 }
				firstjob                     = false
			else
				connections[connector_title] =
					 {
							'fromOperator'  => 'job_' + last_job_id.to_s,
							'fromConnector' => 'output_1',
							'toOperator'    => 'job_' + j.id.to_s,
							'toConnector'   => 'input_1'
					 }
			end
			last_job_id = j.id
			link_count  += 1
		end

		data = JSON.pretty_generate({
			 'operators' => operators,
			 'links'     => connections
		})


		# This is unecessarry, just return the data as a json and set the options in 
		# the JS file so that you can add callback functions to it
		#final_json = JSON.pretty_generate({
		#	                                   'verticalConnection' => 'true',
		#	                                   'data'               => data,
		#	                                   'linkWidth'          => '20',
		#	                                   'grid'               => '25',
		#	                                   'canUserEditLinks' => false,
      	#									   'canUserMoveOperators' => false 
		#                                 })
		#logger.debug 'Funnel-Builder INDEX JSON: ' + final_json.to_s

		render json: data
	end

	def api_index_super

		width       = params[:width]
		campaign_id = params[:campaign_id] # Not used yet

		app_param = params[:app_id]
		app       = App.find(app_param)
		appid     = app.id

		@email_lists = EmailList.where(app_id: appid)

		@local_jobs = Array.new

		left          = 0
		top           = 0
		top_increment = 125 #Top Increment

		operators = Hash.new

		# TODO: Convert all Hash Keys to :key format and change from ' to ' single quotes

		campaign  = Campaign.find(campaign_id)

		operators['campaign_0'] =
			 {
					:top                  => top.to_s,
					:left                 => left.to_s,
					:multipleLinksOnInput => 'true',
					:properties           => {
						 :title   => 'Campaign',
						 :inputs  => {},
						 :outputs => {
								:output_1 => {
									 :label => campaign.name + ' Jobs:',
								}
						 }
					}
			 }

		top   += (top_increment - 28) #First Link doesn't have all boxes so adjust the first link by size of box (28px)

		# TODO: Dynamically calculate a column-count from page-width param

		count = 0 # TODO: Add app_id again - app_id: appid,
		Job.where(campaign_id: campaign.id).each do |j|
			p 'Adding Job ID ' + appid.to_s

			jl                      = JobLocal.new
			jl.local_identifier     = 'job_' + j.id.to_s
			jl.name                 = j.name

			jl.hook_identifier      = campaign.hook_identifier
			jl.hook_id              = j.hook_id
			jl.campaign_id          = j.campaign_id

			jl.subject              = j.subject
			jl.content              = j.content

			jl.email_list_id        = j.email_list_id
			jl.app_id               = j.app_id
			jl.executed             = j.executed
			jl.created_at           = j.created_at
			jl.updated_at           = j.updated_at
			jl.execute_time         = j.execute_time
			jl.execute_set_time     = j.execute_set_time

			total_revenue = 0
			CampaignProductLead.where(job_id: j.id, sold: true, app_id: appid).each do |cel|
				total_revenue += cel.sale_ammount
			end
			jl.total_revenue        = total_revenue

			# Add the execute time to the time it was created to find the next execute time
			date = DateTime.parse(jl.created_at) # Convert Timestamp to DateTime Object
			add_time = jl.execute_time # Get jobs execute time
			date = date + add_time.hours # Add jobs execute time to DateTime Object
			label = date.strftime('%c')

			if jl.executed == true
				executedstring = 'Executed ' + j.execute_set_time
			else
				executedstring = jl.execute_time.to_s + ' hours'
			end

			@local_jobs << jl

			if operator_title = (jl.local_identifier).to_s
				operators[operator_title] =
					 {
							'top'                  => top.to_s,
							'left'                 => left.to_s,
							'multipleLinksOnInput' => 'false',
							'properties'           => {
								 'title'   => j.name,
								 'inputs'  => {
										'input_1' => {
											 'label' => ''
										}
								 },
								 'outputs' => {
										'output_1' => {
											 'label' => executedstring.html_safe
										}
								 }
							}
					 }
				count                     += 1
				top                       += top_increment
			end
		end

		connections = Hash.new
		link_count  = 0
		last_job_id = 0
		firstjob    = true

		Job.where(campaign_id: campaign.id).each do |j|
			connector_title = ('link_' + link_count.to_s).to_s
			if firstjob
				connections[connector_title] =
					 {
							'fromOperator'  => 'campaign_0',
							'fromConnector' => 'output_1',
							'toOperator'    => 'job_' + j.id.to_s,
							'toConnector'   => 'input_1'
					 }
				firstjob                     = false
			else
				connections[connector_title] =
					 {
							'fromOperator'  => 'job_' + last_job_id.to_s,
							'fromConnector' => 'output_1',
							'toOperator'    => 'job_' + j.id.to_s,
							'toConnector'   => 'input_1'
					 }
			end
			last_job_id = j.id
			link_count  += 1
		end

		data = JSON.pretty_generate({
			                             'operators' => operators,
			                             'links'     => connections
		                            })


		# This is unecessarry, just return the data as a json and set the options in
		# the JS file so that you can add callback functions to it
		#final_json = JSON.pretty_generate({
		#	                                   'verticalConnection' => 'true',
		#	                                   'data'               => data,
		#	                                   'linkWidth'          => '20',
		#	                                   'grid'               => '25',
		#	                                   'canUserEditLinks' => false,
		#									   'canUserMoveOperators' => false
		#                                 })
		#logger.debug 'Funnel-Builder INDEX JSON: ' + final_json.to_s

		render json: data
	end

	def superfunnel

app/helpers/funnel_builder_helper.rb
module FunnelBuilderHelper
end

app/views/funnel_builder/fb_campaign_select.html.erb
<script type="text/css">
body {
	  background: #f06d06;
  font-size: 80%;
  padding: 20px;
}

main {
  background: white;
  height: 200px;
  width: 60%;
  margin: 0 auto;
  padding: 20px;
  display: flex;
  justify-content: center;
  align-items: center;
  resize: both;
  overflow: auto;
}

main div {
  background: black;
  color: white;
  width: 50%;
  padding: 20px;
  resize: both;
  overflow: auto;
}


</script>


<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= root_url %>">Mail Funnels</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="<%= root_url %>">Home <span class="sr-only">(current)</span></a></li>
				<li class="active"><a href="<%= funnel_path %>">Mail-Funnel-Builder</a></li>
				<li><a href="<%= campaigns_url %>">Campaigns</a></li>
				<li><a href="<%= root_url %>lists">Email Lists</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<!--<li><a href="#">Link</a></li>-->
			</ul>
		</div>
	</div>
</nav>

<div class="container">

		<!-- Campaign Selector Partial -->
		<div class="col-xs-12">
			<legend>
				<h2>Mail Funnels - Funnel Builder</h2>
			</legend>
			<%= render 'campaign_select' %>
		</div>
		<!-- END Campaign Selector Partial-->
	</div>

</div>

app/views/funnel_builder/superfunnel.html.erb
<% content_for :javascript do %>
		<%= javascript_include_tag 'campaign_funnel_builder_manifest' %>
		<script type="text/javascript">
			window.mainPageTitle = 'Main Page';
			ShopifyApp.ready(function () {
				ShopifyApp.Bar.initialize({
					title: window.mainPageTitle,
					icon: '/shopify.png',
					buttons: {
						secondary: {
							label: "Mail-Funnel Home",
							href: "http://docs.shopify.com/embedded-app-sdk",
							target: 'new'
						}
					}
				});
			});
		</script>
<% end %>

<!-- NAV BAR -->
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= root_url %>">Mail Funnels</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><a href="<%= root_url %>">Home <span class="sr-only">(current)</span></a></li>
				<li class="active"><a href="<%= funnel_path %>">Mail-Funnel-Builder</a></li>
				<li><a href="<%= campaigns_url %>">Campaigns</a></li>
				<li><a href="<%= root_url %>lists">Email Lists</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<!--<li><a href="#">Link</a></li>-->
			</ul>
		</div>
	</div>
</nav>
<!-- END NAV BAR -->


<div class="container">
	<div class="col-xs-12">
		
		<!-- Mail Funnel Builder Title -->
		<legend>
			<h2>Mail Funnel Builder</h2>
		</legend>
		<!-- END Mail Funnel Builder Title -->
		
		<div class="row">
			
			<!-- START RIGHT SIDE PANELS -->
			<div class="col-xs-12 col-sm-6 pull-right">
				
				<!-- Campaign Info Panel -->
				<div class="panel panel-primary">
					
					<!-- Campaign Info Title -->
					<div class="panel-heading">
						<h3 class="panel-title">Campaign Info</h3>
					</div>
					
					<!-- Campaign Info Body -->
					<div class="panel-body">
						<h5><b>Campaign: </b><%= @campaign.name %></h5>
						<h5><b>Hook: </b><%= @hook.name %></h5>
						<h5><b>Email-List: </b><span id="email_list_name"><%= @email_list.name %></span></h5>
						<!-- Hidden Div to hold IDs -->
						<div class="hidden">
							<input type="number" id="current_app_id" value="<%= @app_id %>" />
							<input type="number" id="current_email_list_id_holder" value="<%= @email_list.id %>" />
							<input type="number" id="campaign_id_holder" value="<%= @campaign.id %>"/>
						</div>
						<!-- END Hidden Div -->
					</div>
				
				</div>
				<hr>
				<!-- END Campaign Info Panel -->
				
				<!-- Job Actions Panel -->
				<div class="panel panel-primary">
					
					<!-- Campaign Info Title -->
					<div class="panel-heading">
						<h3 class="panel-title">Job Actions</h3>
					</div>
					
					<!-- Campaign Info Body -->
					<div class="panel-body">
						<button class="btn btn-primary" id="create_button">New Job</button>
						<button class="btn btn-danger" style="" id="delete_selected_button">Delete Selected Job</button>
						<button class="btn btn-success" style="" id="edit_selected_button">Edit Selected Job</button>
					</div>
				
				</div>
				<hr>
				<!-- END Job Actions Panel -->
				
				<!-- Select Campaign Email List Panel -->
				<div class="panel panel-primary">
					
					<!-- Campaign Info Title -->
					<div class="panel-heading">
						<h3 class="panel-title">Change Campaign Email List</h3>
					</div>
					
					<!-- Campaign Info Body -->
					<div class="panel-body">
						<div class="col-xs-12">
							<%= render 'main_interface/email_list_select' %>
						</div>
					</div>
				
				</div>
				<!-- END Selest Campaign Email List Panel -->
			
			</div>
			<!-- END RIGHT SIDE PANELS -->
			
			<!-- START Campaign Funnel Builder Flow Chart -->
			<style>
				.flowchart-operator-title {
					background-color: #008cba !important;
					color: #ffffff;
				}
			</style>
			<div class="col-xs-12 col-sm-6" id="funnel-builder-canvas">
				<input type="number" id="canvas_height_holder" class="hidden" value="<%= @height %>" />
			</div>
			<!-- END Campaign Funnel Builder Flow Chart -->
		
		</div>
	</div>
</div>

<!-- REMOVED ALL JS THAT WAS HERE AND PUT IT IN SEPERATE FILE -->


<!-- RESULT MODAL -->
<div class="modal fade" tabindex="-1" role="dialog" id="result_modal" aria-labelledby="#result_modal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			
			<div class="modal-header" style="background-color: #008cba; color: #ffffff;">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="result_modal_title"></h4>
			</div>
			
			<div class="modal-body text-center">
				<h3 id="result_modal_text"></h3>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" id="node_status_acknowledge" data-dismiss="modal">Okay</button>
			</div>
		</div>
	</div>
</div>
<!-- END RESULT MODAL -->

<!-- DELETE NODE MODAL -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal_node_delete" aria-labelledby="#modal_node_delete">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			
			<div class="modal-header" style="background-color: #008cba; color: #ffffff;">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Delete Job</h4>
			</div>
			
			<div class="modal-body">
				<h4>Are you sure you want to delete the following job?</h4>
				<br>
				
				<!-- Job Info -->
				<div class="list-group">

          <span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Job Name:</strong> <span class="list-group-item-text" id="node_delete_job_name"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Job ID:</strong> <span class="list-group-item-text" id="node_delete_job_id"></span>
            </h6>
            <input type="number" class="hidden" id="node_delete_id_hidden" />
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Email Subject:</strong> <span class="list-group-item-text" id="node_delete_email_subject"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Email Content:</strong> <span class="list-group-item-text" id="node_delete_email_content"></span>
            </h6>
          </span>
				
				</div>
				<!-- END Job Info -->
			
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-danger pull-left" data-dismiss="modal">No, Keep Job</button>
				<button type="button" class="btn btn-success pull-right" id="modal_node_delete_confirm">Yes, Delete Job</button>
			</div>
		
		</div>
	</div>
</div>
<!-- END DELETE NODE MODAL -->

<!-- NEW JOB MODAL -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal_node_create" aria-labelledby="#modal_node_create">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header" style="background-color: #008cba; color: #ffffff;">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Create New Job</h4>
			</div>
			<div class="modal-body">
				
				<form>
					<div class="well">
						<legend>Job</legend>
						<div class="form-group">
							<label for="node_update_job_name" class="control-label"><b>Name:</b></label>
							<input type="text" class="form-control" id="node_new_job_name" placeholder="Enter a name for the job"/>
						</div>
						
						<div class="form-group">
							<label for="node_update_execute_time" class="control-label"><b>Email Execute-Time (Hours after hook is hit):</b></label>
							<input type="number" name="execute_time" class="form-control" id="node_new_job_execute_time" placeholder="How many hours after the hook should we send the followup email"/>
						</div>
					</div>
					
					<hr>
					
					<%= render 'funnel_builder/funnel_builder_modals/job_email_fields.html.erb' %>
					
					<hr>
				</form>
				
				<div class="list-group">

          <span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">App ID:</strong> <span class="list-group-item-text" id="node_new_app_id"><%= @app_id %></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Campaign ID:</strong> <span class="list-group-item-text" id="node_new_campaign_id"><%= @campaign.id %></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Email List ID:</strong> <span class="list-group-item-text" id="node_new_email_list_id"><%= @email_list.id %></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Hook Identifier:</strong> <span class="list-group-item-text" id="node_new_hook_name"><%= @hook.name %></span>
            </h6>
          </span>
				
				</div>
			
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" id="new_job_submit" class="btn btn-primary">Create Job</button>
			</div>
		</div>
	</div>
</div>
<!-- END NEW JOB MODAL -->

<!-- UPDATE JOB MODAL -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal_node_update" aria-labelledby="#modal_node_update">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header" style="background-color: #008cba; color: #ffffff;">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Update Job</h4>
			</div>
			<div class="modal-body">
				
				<form>
					<div class="well">
						<legend>Job</legend>
						<div class="form-group">
							<label for="node_update_job_name" class="control-label"><b>Name:</b></label>
							<input type="text" class="form-control" id="node_update_job_name" placeholder="Enter a name for the job"/>
							<legend>Status</legend>
							<span class="list-group-item">
			          <label for="node_update_execute_time" class="control-label"><b>Send email in how many hours?</b></label>
			          <input type="number" name="execute_time" class="form-control" id="node_update_execute_time" placeholder=""/>
	            </span>
						</div>
					</div>
					
					<hr>
					
					<%= render 'funnel_builder/funnel_builder_modals/job_email_fields.html.erb' %>
					
					<hr>
				</form>
				
				<div class="list-group">
					<!-- TODO: Dynamically fetch the value names from their ID's below -->
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">App ID:</strong> <span id="node_update_app_id"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Campaign ID:</strong> <span class="list-group-item-text" id="node_update_campaign_id"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Job ID:</strong> <span class="list-group-item-text" id="node_update_job_id"></span>
            </h6>
            <input type="number" class="hidden" id="node_id_hidden" />
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Job Local Identifier:</strong> <span class="list-group-item-text" id="node_update_local_identifier"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Email List ID:</strong> <span class="list-group-item-text" id="node_update_email_list_id"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Hook Identifier:</strong> <span class="list-group-item-text" id="node_update_hook_identifier"></span>
            </h6>
          </span>
					
					<span class="list-group-item">
            <h6 class="list-group-item-heading">
            <strong style="color: #008cba;">Executed:</strong> <span class="list-group-item-text" id="node_update_job_executed"></span>
            </h6>
          </span>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" id="update_job_submit" class="btn btn-primary">Update Job</button>
			</div>
		</div>
	</div>
</div>
<!-- END UPDATE JOB MODAL -->