config/routes.rb
Rails.application.routes.draw do
  # MF-CLIENT - ROUTES.RB

  # Main
  root :to => 'main_interface#index'
  get '/campaign/:campaign_id', to: 'main_interface#campaign'
  get '/campaigns', to: 'main_interface#campaigns'
  get '/new_campaign', to: 'main_interface#new_campaign'
  get '/create_campaign', to: 'main_interface#create_campaign'
  get '/edit_campaign/:id', to: 'main_interface#edit_campaign'
  get '/job/:id', to: 'main_interface#job'

  # Funnel-Builder
  get '/funnel/:campaign_id', to: 'funnel_builder#index'
  get '/funnel', to: 'funnel_builder#index'
  get '/mainfb/', to: 'funnel_builder#superfunnel'

  # Funnel-Builder JSON API
  post '/fbapi_index' => 'funnel_builder#api_index'
  post '/fbapi_update' => 'funnel_builder#api_update'
  post '/fbapi_read' => 'funnel_builder#api_read'
  post '/fbapi_create' => 'funnel_builder#api_create'
  post '/fbapi_delete' => 'funnel_builder#api_delete'
  post '/fbapi_update_email_list' => 'funnel_builder#api_update_list' #API Route to update Campaigns Email List

  get '/campaignjobs/:id', to: 'campaigns#viewcampaignjobs'

  # Email Controller
  get '/lists', to: 'email#lists'
  get '/emails/:list_id', to: 'email#emails'
  get '/new_list', to: 'email#new_list'
  match '/create_list' => 'email#create_list', via: [:post]

  # Scaffolds
  # resources :mail_funnel_configs
  # resources :email_lists

  # Shopify Routes
  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'

  mount ShopifyApp::Engine, at: '/'

  # namespace :app_proxy do
  #   root action: 'index'
    # simple routes without a specified controller will go to AppProxyController

    # resources :hooks_constants
    # resources :users
      # resources :campaigns

    # more complex routes will go to controllers in the AppProxy namespace
    # 	resources :reviews
    # GET /app_proxy/reviews will now be routed to
    # AppProxy::ReviewsController#index, for example
  # end
end

app/models/app.rb
class App < RestModel
	has_many :jobs
	has_many :email_lists
	has_many :emails
	has_many :campaigns
	has_many :campaign_product_leads

	def myId()
		# TODO: Verify this works / get it working
		# Get Shopify App Name
		# name = ShopifyAPI::Store::name
		name = 'bluehelmet-dev'
		return App.where(name: name).first.id
	end

	# accepts_nested_attributes_for :campaigns
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < RestModel

	has_one :hook
	belongs_to :app
	has_one :email_list
	has_many :jobs
	belongs_to :app
	has_many :campaign_product_leads

	# accepts_nested_attributes_for :hooks
end

app/models/campaign_product_lead.rb
class CampaignProductLead < RestModel
	belongs_to :app
	belongs_to :campaign
	belongs_to :job
	belongs_to :EmailList
	belongs_to :email
end

app/models/email.rb
class Email  < RestModel
	belongs_to :emails_list

	# parse_root_in_json true, format: :active_model_serializers
	# include_root_in_json true # Remove if anything
	# include_root_in_json :email

	# collection_path "/email_lists/:email_list_id/emails"

	has_many :campaign_product_leads
end

app/models/email_list.rb
class EmailList < RestModel

	has_many :emails
	belongs_to :app
	# has_one :job
	belongs_to :campaign
	has_many :campaign_product_leads
end

app/models/hook.rb
class Hook < RestModel

	has_many  :campaigns
	has_many :jobs
end

app/models/job.rb
class Job < RestModel

	belongs_to :app
	has_one :email_list
	belongs_to :campaign
	has_one           :campaign_product_lead

end

app/models/job_queue.rb
class JobQueue < RestModel

end

app/models/mail_funnel_config.rb
class MailFunnelConfig < ApplicationRecord

	def client_installed
		installed = MailFunnelConfig.where(name: "app_installed")
		if installed.any?
		end
	end

end

app/models/rest_model.rb
require 'active_resource'

class RestModel < ActiveResource::Base
	self.include_format_in_path = false
	self.site = "http://localhost:3001"

	# TODO: SECURITY: Setup JWT or SSL for Client-Server auth

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

app/controllers/email_controller.rb
class EmailController < ShopifyApp::AuthenticatedController
	before_action :set_list_id, only: [:emails]
	before_action :set_email_list, only: [:editlist, :updatelist, :destroylist]
	protect_from_forgery with: :null_session

	def lists

		# appname = BluehelmetUtil.get_shopify_session_app_name
		@app  = BluehelmetUtil.get_app
		@list = EmailList.where(app_id: @app.id)

	end


	def editlist

	end

	def destroylist

	end

	# GET /newlist
	def newlist
	end

	# POST /create_list
	def create_list

		logger.debug 'We made it to create_list'

		app = BluehelmetUtil.get_app

		@email_list = EmailList.new(name: params[:name], description: params[:description], app_id: app.id)

		if @email_list.save
			@message = 'Email list was successfully created.'
		else
			@message = 'Email list was NOT created.'
		end

	end

	def emails

		# appname = BluehelmetUtil.get_shopify_session_app_name
		@app    = BluehelmetUtil.get_app
		@emails = Email.where(email_list_id: @list.id)


	end

	def newemail

	end

	def editemail

	end

	def deleteemail

	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_list_id
		@list = EmailList.find(params[:list_id])
	end

	# Use callbacks to share common setup or constraints between actions.
	def set_email_list
		@email_list = EmailList.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def email_list_params
		params.require(:email_list).permit(:name, :description, :app_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController

  def index
    # @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @hooks_constants = HooksConstant.all

  end

  def modal
  end

  def modal_buttons
  end

  def regular_app_page
  end

  def buttons
  end

  def help
  end

  def error
    raise "An error page"
  end


  def form_page
    if request.post?
      if params[:name].present?
        flash[:notice] = "Created #{ params[:colour] } unicorn: #{ params[:name] }."
      else
        flash[:error] = "Name must be set."
      end
    end
  end

  def pagination
    @total_pages = 3
    @page = (params[:page].presence || 1).to_i
    @previous_page = "/pagination?page=#{ @page - 1 }" if @page > 1
    @next_page = "/pagination?page=#{ @page + 1 }" if @page < @total_pages
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/email_lists_helper.rb
module EmailListsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/jobs_local_helper.rb
module JobsLocalHelper
end

app/views/apps/_form.html.erb
<%= form_for(app) do |f| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :builder_lock %>
    <%= f.check_box :builder_lock %>
  </div>

  <div class="field">
    <%= f.label :auth_token %>
    <%= f.text_field :auth_token %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Builder lock</th>
      <th>Auth token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.builder_lock %></td>
        <td><%= app.auth_token %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Builder lock:</strong>
  <%= @app.builder_lock %>
</p>

<p>
  <strong>Auth token:</strong>
  <%= @app.auth_token %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= root_url %>">Mail Funnels</a>
		</div>
		
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="<%= root_url %>">Home <span class="sr-only">(current)</span></a></li>
				<li><a href="<%= funnel_url %>">Mail-Funnel-Builder</a></li>
				<li><a href="<%= root_url %>lists">Email Lists</a></li>
				<li><a href="<%= root_url %>campaigns">Email Lists</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<!--<li><a href="#">Link</a></li>-->
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8 ;">
	
	<% application_name = ShopifyApp.configuration.application_name %>
	
	<!--SHOPIFY EMBEDDED API -->
	<script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
	
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<!-- BOOTSWATCH PAPER -->
	<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-HzUaiJdCTIY/RL2vDPRGdEQHHahjzwoJJzGUkYjHVzTwXFQ2QN/nVgX7tzoMW3Ov" crossorigin="anonymous">
	
	<!-- Bootstrap JS-->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	<!--JQUERY FLOWCHART-->
	<link href="<%= stylesheet_path "jquery.vertical.flowchart.css" %>" rel="stylesheet" type="text/css">
	<link href="<%= stylesheet_path "funnelstyle.css" %>" rel="stylesheet" type="text/css">
	
	<!--<script-->
	<!--src="https://code.jquery.com/jquery-2.2.4.min.js"-->
	<!--integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="-->
	<!--crossorigin="anonymous"></script>-->
	
	
	<script src="//code.jquery.com/jquery-1.12.2.min.js"></script>
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
	
	
	<script src="<%= javascript_path "jquery.vertical.flowchart.js" %>"></script>
	
	<script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
	<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
	
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
	
	<!-- Latest compiled and minified JavaScript -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
	
	<script type="text/javascript">
		ShopifyApp.init({
			apiKey: "<%= ShopifyApp.configuration.api_key %>",
			shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
			debug: true,
			forceRedirect: true
		});
	</script>
	
	<script>var editor = new MediumEditor('.mediumEditable');</script>
	
	
	<title>Mail-Funnel</title>
	
	<%= csrf_meta_tags %>
</head>

<div id="ajax-messages"></div>

<body>
<div class="app-wrapper">
	<div class="app-content">
		<main role="main">
			<%= yield %>
		</main>
	</div>
</div>


<% if content_for?(:javascript) %>
		<div id="ContentForJavascript" data-turbolinks-temporary>
			<%= yield :javascript %>
		</div>
<% end %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8 ;">
		
		<% application_name = ShopifyApp.configuration.application_name %>
		
		<!--SHOPIFY EMBEDDED API -->
		<script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
		
		<%= stylesheet_link_tag 'application', media: 'all'%>
		<%= javascript_include_tag 'application'%>
		
		<!-- BOOTSTRAP -->
		<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-HzUaiJdCTIY/RL2vDPRGdEQHHahjzwoJJzGUkYjHVzTwXFQ2QN/nVgX7tzoMW3Ov" crossorigin="anonymous">
		
		<!--JQUERY FLOWCHART-->
		<link href="<%= stylesheet_path "jquery.vertical.flowchart.css" %>" rel="stylesheet" type="text/css">
		<link href="<%= stylesheet_path "funnelstyle.css" %>" rel="stylesheet" type="text/css">
		<script src="//code.jquery.com/jquery-1.12.2.min.js"></script>
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
		<script src="<%= javascript_path "jquery.vertical.flowchart.js" %>"></script>
		
		<!--<script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>-->
		<!--<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">-->
		<!---->
		
		<!--BOOTSTRAP JS-->
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
		
		<!-- Latest compiled and minified JavaScript -->
		<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
		
		<script type="text/javascript">
			ShopifyApp.init({
				apiKey: "<%= ShopifyApp.configuration.api_key %>",
				shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
				debug: true,
				forceRedirect: true
			});
		</script>
		
		<script>var editor = new MediumEditor('.mediumEditable');</script>
		
		<title>Mail-Funnel</title>
		
		<%= csrf_meta_tags %>
		
	</head>
	<body>
		
		<div id="ajax-messages"></div>
		
		<div class="app-wrapper">
				<div class="app-content">
					<main role="main">
						<%= yield %>
					</main>
				</div>
			</div>
			
			<% if content_for?(:javascript) %>
					<div id="ContentForJavascript" data-turbolinks-temporary>
						<%= yield :javascript %>
					</div>
			<% end %>
		
		</body>
</html>